### ISSUE TITLE
Arcade MRA ROM Missing

### ISSUE THREAD

**Issue by molnara** [nilp0inter/MiSTer_WebMenu#17]
**Describe the bug**
Arcade games are showing that the ROM is missing, but games run as expected. ROMs are definitely in /media/fat/games/mame and /media/fat/games/hbmame

**Describe your setup**
- WebMenu Version: v0.4.2rc1
- MiSTer Version: v200602

**To Reproduce**
1. Go to 'http://mister'
2. Click on 'Cores'
3. Scroll down to 'Arcade' past the RBFs until you get to the MRA files.
4. You will see ROM Missing as a yellow label next to MRA for each arcade game.

**Expected behavior**
It should only show ROM Missing for games that actually have the ROM missing.

**Screenshots**

![arcade-mra-rom-missing](https://user-images.githubusercontent.com/10979921/83912958-bed92680-a73c-11ea-95cb-efaf05040bbe.png)

**Web Browser:**
 - OS: Windows 10
 - Browser Firefox
 - Version 76

**Comment by nilp0inter** [comment]
This should be fixed here https://github.com/nilp0inter/MiSTer_WebMenu/releases/tag/v0.4.2rc2
