### ISSUE TITLE
MiSTer_WebMenu

### ISSUE THREAD

**Issue by jdelouise** [nilp0inter/MiSTer_WebMenu#2]
**I am giving feedback about:**
MiSTer_WebMenu

**My opinion is:**
This is AWESOME!

**I believe that because:**
It's strange that today at work I was wondering if you could program using a standard language and connect to the mister, and BAM, I come home and PEZZ has a video mentioning your program.  And then the best part is your using the ELM Language!!!,  man, I can't tell you how hyped I am!  Good luck!!!

**But:**
I have not had a chance to play with it but when I do I will try to give some input!

**Comment by nilp0inter** [comment]
Thank you for your kind words.

I am pretty new to Elm but I am having a great time using it for webmenu. I am not a frontend guy by any means but I have a functional background which is really helping me. Right now the code is not pretty, though. 

Please be back after you try it (be sure to use the latest release, previos versions have issues w/ the latest MiSTer)

**Comment by nilp0inter** [comment]
@jdelouise , did you finally try it?
