### ISSUE TITLE
Arcade question/issue

### ISSUE THREAD

**Issue by pividivi** [nilp0inter/MiSTer_WebMenu#3]
**I am giving feedback about:**
WebMenu

**My opinion is:**
Great idea. Good start!

**I believe that because:**
I like to be able to remote control what the mister is running. This way I can sort of make it a "jukebox" to run some demo's or attract modes from arcade cores, without requiring to grab a controller or dig up the keyboard. 

**But:**
The Arcade part of the webmenu does not seem to correspond with the menu structure on the mister menu. I suspect the webmenu only scans for the arcade .rbf's? I think it actually should be scanning and parsing the .mra files. Because in it's current state, you can launch an arcade core, but  most of them do not run correctly; the core is there (loaded, F12 gives you the core menu) but I think the needed rom is not loaded because I only see a black screen outside of the menu.

**Comment by nilp0inter** [comment]
Right now WebMenu does not support `.mra` files, only `.rbf` as you mention, but `.mra` it is the next thing on the roadmap. I expect it to be ready by next week.

I REALLY like the "jukebox" idea! Thank you!

I am opening a couple of issues to improving tracking, one for the `.mra` support and other for the "jukebox" feature.

**Comment by nilp0inter** [comment]
I am closing this issue. You can keep track of both feature requests in #6 and #7.

Thank you very much!

**Comment by nilp0inter** [comment]
Hi @pividivi ,

I've implemented MRA support in https://github.com/nilp0inter/MiSTer_WebMenu/releases/tag/v0.4.0rc2 

I am probably not releasing a stable release until Monday in the mean time it would be very helpful if you can give it a try.

**Comment by pividivi** [comment]
Hi Roberto,

I tried the v0.4 version. There is progress!
I notice the following things:


   - My folder structure in the /_ARCADE folder is as follows:

[image: image.png]
As far as I know this is the standard structure when using the updater
script and the default Retrodriven update script.
With the new version of the WebMenu I seem to be missing all the cores in
the _Jotego, _Sega System 1, _Unofficial and _Alternatives folders.
They are not visible in the WebMenu after a (re)scan.
It would be nice to scan and see them as sub-folders under Arcade in the
Webmenu.
Or prefix the core's name with the dir name/.
Or only see the _Unofficial and _Alternatives folders as sub-folders, while
the _Jotego & _Sega System 1 folders are mixed in with the rest in the
default ARCADE view (the "root" view).

   - While most cores from the "root" folder are visible, some are not
   showing up. For instance Woodpecker.mra (I cán launch it successfully from
   the MiSTer menu)


   - I see 3 Arkanoid mra's in the webmenu that have identical names, But
   in the Mistermenu and on the sd card they have different names, so they can
   be differentiated easier:
   [image: image.png]

   v.s.

       [image: image.png]


   - Almost every mra "block" tells me that the rom is missing. However,
   the roms are there AND the mra/core works when launched from the WebMenu:

[image: image.png]
For instance, the above core shows Missing, but it works correctly when I
launch it.
The only cores that show "ROMs: Found" are: Pong, Computer Space, Pacmanic
Miner and Mr. Do Nightmare

Hopefully my findings will help!

regards, Pieter

Op vr 8 mei 2020 om 01:35 schreef Roberto Abdelkader Martínez Pérez <
notifications@github.com>:

**Comment by nilp0inter** [comment]
Hi @pividivi ,

It looks like you responded via email.  Unfortunately I think Github does not support adding images to email responses, so I don't see them and seems pretty important.

Could you please respond through the Github UI so that the message is well formatted. Also could you do that on issue #6 instead on this one?

Thank you for your time!
