### ISSUE TITLE
Implement `.mra` support

### ISSUE THREAD

**Issue by nilp0inter** [nilp0inter/MiSTer_WebMenu#6]
**Is your feature request related to a problem? Please describe.**
MRA based games does not show properly

**Describe the solution you'd like**
Parse `.mra` files and use its data to show and launch games.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature was first mention by @pividivi in #3 .

**Comment by pividivi** [comment]
tried the v0.4 version. There is progress!
I notice the following things:

- My folder structure in the /_ARCADE folder is as follows: 

    ![image](https://user-images.githubusercontent.com/58731212/81468719-93b4f300-91e1-11ea-8c33-74bbea89e3df.png)

As far as I know this is the standard structure when using the updater script and the default Retrodriven update script.
With the new version of the WebMenu I seem to be missing all the cores in the _Jotego, _Sega System 1, _Unofficial and _Alternatives folders.
They are not visible in the WebMenu after a (re)scan.
It would be nice to scan and see them as sub-folders under Arcade in the Webmenu.
Or prefix the core's name with the dir name/.
Or only see the _Unofficial and _Alternatives folders as sub-folders, while the _Jotego & _Sega System 1 folders are mixed in with the rest in the default ARCADE view (the "root" view).

- While most cores from the "root" folder are visible, some are not showing up. For instance Woodpecker.mra (I cán launch it successfully from the MiSTer menu)

- I see 3 Arkanoid mra's in the webmenu that have identical names, But in the Mistermenu and on the sd card they have different names, so they can be differentiated easier:
    ![image](https://user-images.githubusercontent.com/58731212/81468774-ee4e4f00-91e1-11ea-9033-e13a22bacde4.png)
  
    versus

    ![image](https://user-images.githubusercontent.com/58731212/81468790-0aea8700-91e2-11ea-9022-eed2d756facb.png)

- Almost every mra "block" tells me that the rom is missing. However, the roms are there AND the mra/core works when launched from the WebMenu:

    ![image](https://user-images.githubusercontent.com/58731212/81468837-3b322580-91e2-11ea-83b3-9633740c8c5b.png)
 
For instance, the above core shows Missing, but it works correctly when I launch it.
The only cores that show "ROMs: Found" are: _Pong, Computer Space, Pacmanic Miner and Mr. Do Nightmare_

Hopefully my findings will help!

**Comment by pividivi** [comment]
I tried rc4 and now the roms show “found” instead of missing.
Like the images! Not every rom is found but that may be because of the names.

Speaking of names... the computer/console cores get their names from the filename of the .rbf i think? Maybe an alternative could be to use the names.txt file in the root (if it’s available). That file is optional, but when available it replaces the corenames with more readable and more informative names in the MiSTer menu. _Minimig_ for instance gets replaced with _Comodore Amiga_.
You can read about the names.txt file here: http://www.atari-forum.com/viewtopic.php?f=117&t=38542&p=397172&hilit=Name+list#p397172

I also noticed that The webmenu now shows all the cores in the subfolders. In practice however, it creates a huge block of links at the top of the page, as you might have noticed. Is it possible to put them under a separate option, just like cps1 and console for instance? So you see at the top:
Computer, console, utility, other, arcade, arcade alternatives, arcade unofficial, jotego?

**Comment by nilp0inter** [comment]
Hi! @pividivi ,

thank you for the feedback it is been super useful to me.

I've just published [rc5](https://github.com/nilp0inter/MiSTer_WebMenu/releases/tag/v0.4.0rc5) with an almost complete overhaul of the Cores section. Could you please try it out and tell me what you think?

Regarding the names, exactly, now I use the rbf filename. But I am planning to load all metadata (including names, images, core developers...) from data files in this github repo, this way anybody can contribute to it just by doing a pull-request.

I didn't know about the `names.txt` file , this would be a great starting point for the metadata files I've just mention.

**Comment by pividivi** [comment]
This looks better than the rc4 version!
I like the ordening in subfolders. A very minor request: can you make the default "Cores" screen show the SD Card expanded? Like: 
    ![afbeelding](https://user-images.githubusercontent.com/58731212/81508382-1930c400-9304-11ea-8b6a-16069acd92a3.png)

It took me a minute before I realised that clicking the triangle resulted in more options....
When you start expanded, you immediately can go to consoles or computers; it saves a mouseclick and gives the 1st time user more clarity.

Also, I (and al lot of other people) have connected an USB external drive. There are no cores on it, but it contains the games/HD images of for instance SNES and Amiga (minimig). Are you planning on scanning the USB disk in future implementations of the WebMenu? Note that I (and again, others) have the games archived (zip files), for instance the Smokemonster/Everdrive packs are archives. Will scanning these be a problem?

In the subfolders _Alternatives_ and _Jotego_ etc. I still see some mra's with roms _Missing_ But they work correctly if launched.

**Comment by nilp0inter** [comment]
I added the code to maintain the tree open and changed the triangles to folder icons.

Answering your question, yes, I am planning on adding support for scanning other drives in the future.  But first I have to implement game scanning and launching.

The zip files shouldn't be a problem, but will make the scanning process slower for sure.

I am going to take a look at the rom missing error and I'll try to release a stable version tonight.
